name:                Advent of Code
version:             0.1.0.0
github:              "thomasrules2000/Advent-of-Code"
license:             BSD3
author:              "Thomas Stacey"
maintainer:          "Thomas.Stacey@warwick.ac.uk"
copyright:           "2020 Thomas Stacey"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Cskell#readme>

dependencies:
- base >= 4.7 && < 5
- containers == 0.6.0.1
- split >= 0.2.3
- vector == 0.12.1.2
- matrix == 0.3.6.1

library:
  source-dirs: src
  default-extensions:
    - ApplicativeDo

executables:
  Cskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Cskell

tests:
  Cskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Cskell
