module Main where
    import Days.Day01 (runDay)
    import Days.Day02 (runDay)
    import Days.Day03 (runDay)
    import Days.Day04 (runDay)
    import Days.Day05 (runDay)
    import Days.Day06 (runDay)
    import Days.Day07 (runDay)
    import Days.Day08 (runDay)
    import Days.Day09 (runDay)
    import Days.Day10 (runDay)
    import Days.Day11 (runDay)
    import Days.Day12 (runDay)
    import Days.Day13 (runDay)
    import Days.Day14 (runDay)
    import Days.Day15 (runDay)
    import Days.Day16 (runDay)
    import Days.Day17 (runDay)
    import Days.Day18 (runDay)
    import Days.Day19 (runDay)
    import Days.Day20 (runDay)
    import Days.Day21 (runDay)
    import Days.Day22 (runDay)

    main :: IO ()
    main = do
        putStrLn "Hello World"